DEFAULT_BASE_FRAME_ID = "camera_link"
DEFAULT_DEPTH_FRAME_ID = "camera_depth_frame"
DEFAULT_INFRA1_FRAME_ID = "camera_infra1_frame"
DEFAULT_INFRA2_FRAME_ID = "camera_infra2_frame"
DEFAULT_COLOR_FRAME_ID = "camera_color_frame"
DEFAULT_FISHEYE_FRAME_ID = "camera_fisheye_frame"
DEFAULT_IMU_FRAME_ID = "camera_imu_frame"

DEFAULT_DEPTH_OPTICAL_FRAME_ID = "camera_depth_optical_frame"
DEFAULT_INFRA1_OPTICAL_FRAME_ID = "camera_infra1_optical_frame"
DEFAULT_INFRA2_OPTICAL_FRAME_ID = "camera_infra2_optical_frame"
DEFAULT_COLOR_OPTICAL_FRAME_ID = "camera_color_optical_frame"
DEFAULT_FISHEYE_OPTICAL_FRAME_ID = "camera_fisheye_optical_frame"
DEFAULT_ACCEL_OPTICAL_FRAME_ID = "camera_accel_optical_frame"
DEFAULT_GYRO_OPTICAL_FRAME_ID = "camera_gyro_optical_frame"
DEFAULT_IMU_OPTICAL_FRAME_ID = "camera_imu_optical_frame"

DEFAULT_ALIGNED_DEPTH_TO_COLOR_FRAME_ID = "camera_aligned_depth_to_color_frame"
DEFAULT_ALIGNED_DEPTH_TO_INFRA1_FRAME_ID = "camera_aligned_depth_to_infra1_frame"
DEFAULT_ALIGNED_DEPTH_TO_INFRA2_FRAME_ID = "camera_aligned_depth_to_infra2_frame"
DEFAULT_ALIGNED_DEPTH_TO_FISHEYE_FRAME_ID = "camera_aligned_depth_to_fisheye_frame"
